services:
  service-1:
    image: jaeger/fast-api-app:latest
    ports:
      - 3002:3001
    environment:
      - OTHER_SERVICE=service-2
      - OTHER_SERVICE_PORT=3001
      - OTEL_EXPORTER_JAEGER_HOST=jaeger
      - TRACE_PROVIDER_NAME=fastapi-jaeger-service-1
    container_name: service-1
  service-2:
    image: jaeger/fast-api-app:latest
    ports:
      - 3003:3001
    environment:
      - OTHER_SERVICE=service-1
      - OTHER_SERVICE_PORT=3001
      - OTEL_EXPORTER_JAEGER_HOST=jaeger
      - TRACE_PROVIDER_NAME=fastapi-jaeger-service-2
    container_name: service-2
  jaeger:
    image: jaegertracing/all-in-one:1.6.0
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
    container_name: jaeger
